package com.jetbrains.deepbugs.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class DeepBugsGUI {
    private JLabel thresholdLabel;
    private JPanel rootPanel;
    private JSlider thresholdSlider;
    private JButton setDefault;

    public DeepBugsGUI() {
        setDefault.addActionListener( e -> thresholdSlider.setValue(89));
    }

    public JComponent getRootPanel() {
        return rootPanel;
    }

    public double getThreshold() {
        return (double) thresholdSlider.getValue() / 100.0;
    }

    public void setThreshold(double value) {
        thresholdSlider.setValue((int) (value * 100.0));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), 2, 2, false, true));
        rootPanel.setEnabled(true);
        thresholdLabel = new JLabel();
        thresholdLabel.setText("Threshold, %");
        rootPanel.add(thresholdLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        thresholdSlider = new JSlider();
        thresholdSlider.setMajorTickSpacing(10);
        thresholdSlider.setMinorTickSpacing(1);
        thresholdSlider.setPaintLabels(true);
        thresholdSlider.setPaintTicks(true);
        thresholdSlider.setPaintTrack(true);
        thresholdSlider.setSnapToTicks(true);
        thresholdSlider.setValue(0);
        thresholdSlider.setValueIsAdjusting(false);
        thresholdSlider.putClientProperty("JSlider.isFilled", Boolean.FALSE);
        thresholdSlider.putClientProperty("Slider.paintThumbArrowShape", Boolean.FALSE);
        thresholdSlider.putClientProperty("html.disable", Boolean.FALSE);
        rootPanel.add(thresholdSlider, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
